server:
  port: ${port:8093}
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: demo
  messages:
    encoding: UTF-8
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  datasource:
     driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
     url: jdbc:sqlserver://127.0.0.1:1433;Database=Project_Data
     username: sa
     password: j98390941
  jpa:
    show-sql: true
    database: SQL_SERVER 
    hibernate:      
        ddl-auto: update     
    properties.hibernate.dialect: org.hibernate.dialect.SQLServer2008Dialect
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
  